dataset_params:
  data_dir: "data/train_set/processed"
  labels_file: "data/train_set/labels.json"
  generalized_classes: True
  df_columns:
    - time: ['Time']
    - imu_columns: ['linear_acceleration.x', 'linear_acceleration.y', 'linear_acceleration.z', 'angular_velocity.x', 'angular_velocity.y', 'angular_velocity.z']
    - power_columns: ['mean_power_left', 'mean_power_right']
bag_path: "data/train_set/raw/laminate_flooring/4W/1"
seed: 0
